parameters:
     bbit_audit_log.service.class: BBIT\AuditLogBundle\Services\AuditLogService

services:
#    bbit_audit_log.example:
#        class: %bbit_audit_log.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bbit_audit_log.service:
        class: %bbit_audit_log.service.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
